#+TITLE: Àite

* Keywords
 - Epic :: larg in scope, grand scale, long time
 - colonial :: exploration, competition, frontier, defying odds, settling
 - space :: plants, universe, solar systems, alien life, abundance and scarcity
 - strategy :: explore, settle, discover, compete with other colonies for
               resources, for discovery
 - baxterian :: think xeelee, ultimate crafters of the universe all but unseen;
                think lovecraft, unknowable otherwordly rulers and gods
* Program Structure
 - server
   - server simulates universe and processes events
   - events are generated by "colonials" (players and computer players) and by
     "nature": natural events like solar decay, planets colliding,
     atmospheric/climate changes, and so on
 - client
   - controls an agent
   - colonial decides a "strategy": a short or long term set of orders for the
     colony to pursue
   - can be simple "focus on expansion" or more complex "focus on expansion
     unless resources are low, then focus on gathering and discovery". This
     will be defined through a simple "scripting" language
 - Universe
   - contains everything (i.e. Galaxies)
   - main "sim" runner class
   - contains a list of Colonials operating in the Universe
 - Galaxy
   - container of (solar) Systems
   - Galaxies move through the universe
 - System
   - container of Planets
   - Colonies settle Planets and inhabit Systems
 - Planet
   - has properties (size, mass, temperature, pressure) which affect, generally,
     survivability.
   - Contains slew of elements which then dictate climate
   - Has History which defines the *cultural* things that can be found,
     depending on the age of the planet
 - History
   - A generated set of list of connected events that have happened over the
     course of the planet's lifetime
   - Longer the history, the more the events develop
   - History may add to what the colony can gain from the planet (lifeforms,
     unusually abundant minerals, abandonded technologies, other signs of life)
 - Historical Event
   - One piece of a historical story
* Gameplay
  - Colony starts on a planet
  - Exploration will (generate if necessary) nearby planets and solar systems
  - Technological advancement required for exploration *efficiently*
  - Focusing on resource gathering will limit lifespan of the planet, perhaps
    irrevocably altering atmosphere in a harmful manner
  - Game tracks colony size, resources (material, energy, food, culture,
    knowledge, religion), mood (colony will have desires), habitat
  - player will, for the most part, be in the dark about this.
  - contact between player and game is in the form of small digests, updating on
    happenings in the colony and results of current set of orders
  - however, player can take the time to explore their colony: see what's
    happening, what the mood is, and so on. This is an opportunity ripe for
    checking out discoveries the people have made, changes and updates to
    society and so on.
** Technology
** Culture
** Expansion
* (Chemical) Elements
  - Everything in the universe will come from the periodic table
  - Gases, metals, some liquids, combinations; all form to make the basis of
    the planets, satellites, the universe
  - combinations are important as this describes the chemistry and makeup of
    the planet (water+carbon-chains? life!) Other forms of life?
* Planets
  - climate is defined by temperature, density, atmospheric pressure, and
    elemental composition.
  - averages give and overall view; highs and lows give some indication of what
    kind of biomes are on the planet
  - atmospheric pressure defines whether there is an atmosphere to begin with,
    but also how much of it. Large pressure differential signifies winds or
    storms.
  - components of the planet, the moisture, the air will depend on the pressure
    and temperature. There could be rivers of water; or of molten glass. There
    could be nitrogen rich atmosphere, or there could be hydrogen plasma.
  - Fauna and flora should be on the planet, if sustainable. for the most part,
    there should only be life where oxygen and carbon exist. Only in rare
    circumstances should exceptional (non carbon-based) flora/fauna be found.
  - The planet should have *history*: if it can sustain life, there should be the
    possibility that it has sustained life. There should be archeaological
    finds, or other signs.
  - A planet visited by a colony can be described. The *detail* of the
    description will depend on the technological advancement of the colony, the
    time spent on the planet, and their *focus* (i.e. do they care enough about
    culture or history to look for archeaology?)

* Solar Systems
** Asteroids
** Stars
** Black Holes
** Nebulae
* Galaxies
* Colonies
  - Colonies are groups of people seeking to explore and expand through the
    territories of the universe.
  - A colony will grow and thrive on a planet, but will eventually need to move
    onward, seeking new lands and materials.
  - They can only explore where they can; their *technology* will hold them
    back if they can't survive on a planet, or if they can't detect if a planet
    contains what they desire.
* History
  - planets and systems will have a coherent history; planets in the same
    system, if one supports life then it probably does and the other planets
    will have been colonised.
  - These xeno-colonies will perhaps linger on, or perhaps they will be
    gone. Either way there will be evidence of their existence.
