#+TITLE: Àite

* Keywords
 - Epic :: larg in scope, grand scale, long time
 - colonial :: exploration, competition, frontier, defying odds, settling
 - space :: plants, universe, solar systems, alien life, abundance and scarcity
 - strategy :: explore, settle, discover, compete with other colonies for
               resources, for discovery
 - baxterian :: think xeelee, ultimate crafters of the universe all but unseen;
                think lovecraft, unknowable otherwordly rulers and gods
* Structure
** General
  - server
    - server simulates universe and processes events
    - events are generated by "colonials" (players and computer players) and by
      "nature": natural events like solar decay, planets colliding,
      atmospheric/climate changes, and so on
  - client
    - controls an agent
    - colonial decides a "strategy": a short or long term set of orders for the
      colony to pursue
    - can be simple "focus on expansion" or more complex "focus on expansion
      unless resources are low, then focus on gathering and discovery". This
      will be defined through a simple "scripting" language
  - Universe
    - contains everything (i.e. Galaxies)
    - main "sim" runner class
    - contains a list of Colonials operating in the Universe
  - Galaxy
    - container of (solar) Systems
    - Galaxies move through the universe
  - System
    - container of Planets
    - Colonies settle Planets and inhabit Systems
** Gameplay
   - Colony starts on a planet
   - Exploration will (generate if necessary) nearby planets and solar systems
   - Technological advancement required for exploration *efficiently*
   - Focusing on resource gathering will limit lifespan of the planet, perhaps
     irrevocably altering atmosphere in a harmful manner
   - Game tracks colony size, resources (material, energy, food, culture,
     knowledge, religion), mood (colony will have desires), habitat
   - player will, for the most part, be in the dark about this.
   - contact between player and game is in the form of small digests, updating on
     happenings in the colony and results of current set of orders
   - however, player can take the time to explore their colony: see what's
     happening, what the mood is, and so on. This is an opportunity ripe for
     checking out discoveries the people have made, changes and updates to
     society and so on.
** Elements
   - Everything in the universe will come from a periodic table; but perhaps a
     fictionalised and simplified version of our own.
   - Gases, metals, (some liquids), combinations; all form to make the basis of
     the planets, satellites, the universe
** Planets
   - climate is defined by temperature and humidity
   - averages give and overall view; highs and lows give some indication of what
     kind of biomes are on the planet
   - water coverage may change over time depeding on the pressure, temperature
     and humidity.
   - atmospheric pressure defines whether there is an atmosphere to begin with,
     but also how much of it. Large pressure differential signifies winds or
     storms.
   - components of the planet, the moisture, the air will depend on the pressure
     and temperature. There could be rivers of water; or of molten glass. There
     could be nitrogen rich atmosphere, or there could be hydrogen plasma.
   - Fauna and flora should be on the planet, if sustainable. for the most part,
     there should only be life where ersatz oxygen and carbon exist. Only in
     rare circumstances should exceptional flora/fauna be found.
   - The planet should have history: if it can sustain life, there should be the
     possibility that it has sustained life. There should be archeaological
     finds, or other signs.

